package com.ipca.dms_api.service;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import com.ipca.dms_api.dto.InvoiceDocumentResponse;

import jakarta.annotation.PostConstruct;

@Service
public class InvoiceDocumentService {

    private static final long MAX_FILE_SIZE = 1024 * 1024;

    private final JdbcTemplate invoiceJdbcTemplate;

    @Value("${dms.upload.directory}")
    private String uploadBaseDir;

    public InvoiceDocumentService(@Qualifier("invoiceDataSource") DataSource invoiceDataSource) {
        this.invoiceJdbcTemplate = new JdbcTemplate(java.util.Objects.requireNonNull(invoiceDataSource));
    }

    @PostConstruct
    public void init() {
        // Use identity column syntax compatible with H2 (and modern SQL)
        invoiceJdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS DMS_INVOICE_DOCUMENTS (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    INVOICE_NUMBER VARCHAR(50) NOT NULL,
                    FILE_NAME VARCHAR(150) NOT NULL,
                    FILE_PATH VARCHAR(500) NOT NULL,
                    COMPANY_ID VARCHAR(20),
                    LOCATION_ID VARCHAR(20),
                    DIVISION_NAME VARCHAR(60),
                    APPLICATION_NAME VARCHAR(80),
                    CREATED_BY VARCHAR(50),
                    CREATED_ON TIMESTAMP,
                    CONSTRAINT UQ_DMS_INVOICE_NUMBER UNIQUE (INVOICE_NUMBER)
                )
                """);
                
        invoiceJdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS DMS_INVOICE_OTHER_FILES (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    INVOICE_NUMBER VARCHAR(50) NOT NULL,
                    FILE_NAME VARCHAR(150) NOT NULL,
                    FILE_PATH VARCHAR(500) NOT NULL,
                    CREATED_BY VARCHAR(50),
                    CREATED_ON TIMESTAMP,
                    CONSTRAINT FK_INVOICE_NUMBER FOREIGN KEY (INVOICE_NUMBER) REFERENCES DMS_INVOICE_DOCUMENTS(INVOICE_NUMBER)
                )
                """);


    }

    public boolean exists(String invoiceNumber) {
        Integer count = invoiceJdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM DMS_INVOICE_DOCUMENTS WHERE UPPER(INVOICE_NUMBER) = UPPER(?)",
                Integer.class,
                clean(invoiceNumber));
        return count != null && count > 0;
    }

    public List<String> suggestInvoiceNumbers(String query) {
        if (query == null || query.trim().isEmpty()) {
            return List.of();
        }
        String sql = "SELECT INVOICE_NUMBER FROM DMS_INVOICE_DOCUMENTS WHERE UPPER(INVOICE_NUMBER) LIKE UPPER(?) ORDER BY INVOICE_NUMBER FETCH NEXT 15 ROWS ONLY";
        return invoiceJdbcTemplate.queryForList(sql, String.class, "%" + query.trim() + "%");
    }

    public InvoiceDocumentResponse saveInvoice(
            String invoiceNumber,
            String companyId,
            String locationId,
            String divisionName,
            String applicationName,
            String userId,
            MultipartFile invoiceFile) throws IOException {

        String cleanedInvoice = clean(invoiceNumber);
        if (cleanedInvoice == null || cleanedInvoice.isBlank()) {
            throw new IllegalArgumentException("Invoice number is required.");
        }
        if (invoiceFile == null || invoiceFile.isEmpty()) {
            throw new IllegalArgumentException("Invoice PDF is required.");
        }
        if (invoiceFile.getSize() > MAX_FILE_SIZE) {
            throw new IllegalArgumentException("File size must be 1 MB or less.");
        }
        String originalName = Objects.requireNonNull(invoiceFile.getOriginalFilename(), "File name is required.");
        if (!originalName.toLowerCase().endsWith(".pdf")) {
            throw new IllegalArgumentException("Only PDF files are allowed.");
        }
        if (exists(cleanedInvoice)) {
            throw new IllegalArgumentException("Invoice number already exists.");
        }

        String safeFileName = cleanedInvoice + ".pdf";
        String uploadDir = uploadBaseDir + "/InvoiceDocument/" + valueOrDefault(companyId, "NA") + "/"
                + valueOrDefault(locationId, "NA") + "/" + cleanedInvoice + "/";
        File dir = new File(uploadDir);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        Path fullPath = Paths.get(uploadDir, safeFileName);
        Files.write(fullPath, invoiceFile.getBytes());

        LocalDateTime now = LocalDateTime.now();
        invoiceJdbcTemplate.update("""
                INSERT INTO DMS_INVOICE_DOCUMENTS
                (INVOICE_NUMBER, FILE_NAME, FILE_PATH, COMPANY_ID, LOCATION_ID, DIVISION_NAME, APPLICATION_NAME, CREATED_BY, CREATED_ON)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                cleanedInvoice, safeFileName, fullPath.toString(), companyId, locationId,
                divisionName, applicationName, userId, Timestamp.valueOf(now));

        return findByInvoiceNumber(cleanedInvoice);
    }

    public InvoiceDocumentResponse attachOtherFile(String invoiceNumber, String userId, MultipartFile otherFile) throws IOException {
        String cleanedInvoice = clean(invoiceNumber);
        if (cleanedInvoice == null || cleanedInvoice.isBlank()) {
            throw new IllegalArgumentException("Invoice number is required.");
        }
        if (!exists(cleanedInvoice)) {
            throw new IllegalArgumentException("Invoice number does not exist.");
        }
        if (otherFile == null || otherFile.isEmpty()) {
            throw new IllegalArgumentException("File is required.");
        }
        if (otherFile.getSize() > MAX_FILE_SIZE) {
            throw new IllegalArgumentException("File size must be 1 MB or less.");
        }
        String originalName = Objects.requireNonNull(otherFile.getOriginalFilename(), "File name is required.");
        if (!originalName.toLowerCase().endsWith(".pdf")) {
            throw new IllegalArgumentException("Only PDF files are allowed.");
        }
        
        String safeFileName = originalName.replaceAll("[&,]", "-");
        InvoiceDocumentResponse parent = findByInvoiceNumber(cleanedInvoice);
        String uploadDir = uploadBaseDir + "/InvoiceDocument/" + valueOrDefault(parent.getCompanyId(), "NA") + "/"
                + valueOrDefault(parent.getLocationId(), "NA") + "/" + cleanedInvoice + "/other/";
        File dir = new File(uploadDir);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        Path fullPath = Paths.get(uploadDir, safeFileName);
        Files.write(fullPath, otherFile.getBytes());

        LocalDateTime now = LocalDateTime.now();
        invoiceJdbcTemplate.update("""
                INSERT INTO DMS_INVOICE_OTHER_FILES
                (INVOICE_NUMBER, FILE_NAME, FILE_PATH, CREATED_BY, CREATED_ON)
                VALUES (?, ?, ?, ?, ?)
                """,
                cleanedInvoice, safeFileName, fullPath.toString(), userId, Timestamp.valueOf(now));

        return parent;
    }

    public Page<InvoiceDocumentResponse> search(String invoiceNumber, String locationId, int page, int size) {
        Pageable pageable = PageRequest.of(page, size);
        String invoiceFilter = emptyToNull(invoiceNumber);
        String locationFilter = emptyToNull(locationId);

        String where = " WHERE (? IS NULL OR UPPER(d.INVOICE_NUMBER) LIKE UPPER(?)) "
                + "AND (? IS NULL OR d.LOCATION_ID = ?) ";

        Long total = invoiceJdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM DMS_INVOICE_DOCUMENTS d LEFT JOIN DMS_INVOICE_OTHER_FILES o ON d.INVOICE_NUMBER = o.INVOICE_NUMBER" + where,
                Long.class,
                invoiceFilter, invoiceFilter == null ? null : "%" + invoiceFilter + "%",
                locationFilter, locationFilter);

        List<InvoiceDocumentResponse> rows = invoiceJdbcTemplate.query("""
                SELECT d.ID as d_id, d.INVOICE_NUMBER, d.FILE_NAME as d_fileName, d.FILE_PATH as d_filePath, 
                       d.COMPANY_ID, d.LOCATION_ID, d.DIVISION_NAME, d.APPLICATION_NAME, 
                       COALESCE(o.CREATED_BY, d.CREATED_BY) as CREATED_BY, 
                       COALESCE(o.CREATED_ON, d.CREATED_ON) as CREATED_ON,
                       o.ID as o_id, o.FILE_NAME as o_fileName, o.FILE_PATH as o_filePath
                FROM DMS_INVOICE_DOCUMENTS d 
                LEFT JOIN DMS_INVOICE_OTHER_FILES o ON d.INVOICE_NUMBER = o.INVOICE_NUMBER
                """ + where + " ORDER BY d.CREATED_ON DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY",
                (rs, rowNum) -> InvoiceDocumentResponse.builder()
                        .id(rs.getLong("d_id"))
                        .invoiceNumber(rs.getString("INVOICE_NUMBER"))
                        .fileName(rs.getString("d_fileName")) // for backward compatibility
                        .filePath(rs.getString("d_filePath"))
                        .companyId(rs.getString("COMPANY_ID"))
                        .locationId(rs.getString("LOCATION_ID"))
                        .divisionName(rs.getString("DIVISION_NAME"))
                        .applicationName(rs.getString("APPLICATION_NAME"))
                        .createdBy(rs.getString("CREATED_BY"))
                        .createdOn(rs.getTimestamp("CREATED_ON") == null ? null : rs.getTimestamp("CREATED_ON").toLocalDateTime())
                        .invoiceFileName(rs.getString("d_fileName"))
                        .otherFileName(rs.getString("o_fileName"))
                        .otherFileId(rs.getObject("o_id", Long.class))
                        .build(),
                invoiceFilter, invoiceFilter == null ? null : "%" + invoiceFilter + "%",
                locationFilter, locationFilter, page * size, size);

        return new PageImpl<>(rows, pageable, total == null ? 0 : total);
    }

    public InvoiceDocumentResponse findById(Long id) {
        return invoiceJdbcTemplate.queryForObject(
                "SELECT * FROM DMS_INVOICE_DOCUMENTS WHERE ID = ?",
                (rs, rowNum) -> mapRow(
                        rs.getLong("ID"),
                        rs.getString("INVOICE_NUMBER"),
                        rs.getString("FILE_NAME"),
                        rs.getString("FILE_PATH"),
                        rs.getString("COMPANY_ID"),
                        rs.getString("LOCATION_ID"),
                        rs.getString("DIVISION_NAME"),
                        rs.getString("APPLICATION_NAME"),
                        rs.getString("CREATED_BY"),
                        rs.getTimestamp("CREATED_ON")),
                id);
    }

    public String getOtherFilePath(Long otherFileId) {
        return invoiceJdbcTemplate.queryForObject(
                "SELECT FILE_PATH FROM DMS_INVOICE_OTHER_FILES WHERE ID = ?",
                String.class,
                otherFileId);
    }

    private InvoiceDocumentResponse findByInvoiceNumber(String invoiceNumber) {
        return invoiceJdbcTemplate.queryForObject(
                "SELECT * FROM DMS_INVOICE_DOCUMENTS WHERE UPPER(INVOICE_NUMBER) = UPPER(?)",
                (rs, rowNum) -> mapRow(
                        rs.getLong("ID"),
                        rs.getString("INVOICE_NUMBER"),
                        rs.getString("FILE_NAME"),
                        rs.getString("FILE_PATH"),
                        rs.getString("COMPANY_ID"),
                        rs.getString("LOCATION_ID"),
                        rs.getString("DIVISION_NAME"),
                        rs.getString("APPLICATION_NAME"),
                        rs.getString("CREATED_BY"),
                        rs.getTimestamp("CREATED_ON")),
                invoiceNumber);
    }

    private InvoiceDocumentResponse mapRow(
            Long id,
            String invoiceNumber,
            String fileName,
            String filePath,
            String companyId,
            String locationId,
            String divisionName,
            String applicationName,
            String createdBy,
            Timestamp createdOn) {
        return InvoiceDocumentResponse.builder()
                .id(id)
                .invoiceNumber(invoiceNumber)
                .fileName(fileName)
                .filePath(filePath)
                .companyId(companyId)
                .locationId(locationId)
                .divisionName(divisionName)
                .applicationName(applicationName)
                .createdBy(createdBy)
                .createdOn(createdOn == null ? null : createdOn.toLocalDateTime())
                .build();
    }

    private String clean(String value) {
        return value == null ? null : value.trim().toUpperCase();
    }

    private String emptyToNull(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }

    private String valueOrDefault(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }
}
