spring.application.name=dms-api
spring.security.enabled=false

# ===== Other =====
spring.thymeleaf.cache=false
logging.level.org.springframework=INFO
server.port=8083
server.servlet.session.cookie.name=DMSAPISESSIONID
spring.devtools.restart.enabled=true
spring.devtools.restart.exclude=**/static/**,**/public/**
spring.devtools.livereload.enabled=true

# ===== Oracle DMS DB Config =====
spring.datasource.primary.url=jdbc:oracle:thin:@10.1.1.204:1527:dmsdevdb
spring.datasource.primary.username=dmsinhouse
spring.datasource.primary.password=dmsdev
spring.datasource.primary.driver-class-name=oracle.jdbc.OracleDriver

# ===== Oracle SCM DB Config =====
spring.datasource.scm.url=jdbc:oracle:thin:@10.1.1.23:1526:IPCASCMD
spring.datasource.scm.username=IPCAPROD
spring.datasource.scm.password=IPCAPROD
spring.datasource.scm.driver-class-name=oracle.jdbc.OracleDriver

# ===== Oracle HRMS DB Config =====
spring.datasource.hrms.url=jdbc:oracle:thin:@10.1.1.22:1526:hrmsdb
spring.datasource.hrms.username=hrms_live
spring.datasource.hrms.password=hrms_live
spring.datasource.hrms.driver-class-name=oracle.jdbc.OracleDriver

#=======Email=========
spring.mail.host=EmailRelaySrv.ipca.com
spring.mail.port=587
spring.mail.username=dms.administrator@ipca.com
spring.mail.password=dm$2Dm1n14
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=EmailRelaySrv.ipca.com

# ===== File Upload Directory =====
dms.upload.directory=D:/dms-uploads