spring.application.name=dms-api

# Enable Spring Security (was false for legacy testing)
spring.security.enabled=true

# ===== Other =====
spring.thymeleaf.cache=false
logging.level.org.springframework=INFO
server.port=8083
server.servlet.session.cookie.name=DMSAPISESSIONID
spring.devtools.restart.enabled=true
spring.devtools.restart.exclude=**/static/**,**/public/**
spring.devtools.livereload.enabled=true

# ===== Oracle Primary DB Config =====
spring.datasource.primary.url=jdbc:oracle:thin:@10.1.1.204:1527:dmsdevdb
spring.datasource.primary.username=dmsinhouse
spring.datasource.primary.password=dmsdev
spring.datasource.primary.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# H2 console for development
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== H2 SCM DB Config =====
spring.datasource.scm.url=jdbc:h2:file:./data/scmdb;DB_CLOSE_DELAY=-1;MODE=Oracle
spring.datasource.scm.username=sa
spring.datasource.scm.password=
spring.datasource.scm.driver-class-name=org.h2.Driver

# ===== H2 HRMS DB Config =====
spring.datasource.hrms.url=jdbc:h2:file:./data/hrmsdb;DB_CLOSE_DELAY=-1;MODE=Oracle
spring.datasource.hrms.username=sa
spring.datasource.hrms.password=
spring.datasource.hrms.driver-class-name=org.h2.Driver

#=======Email=========
spring.mail.host=EmailRelaySrv.ipca.com
spring.mail.port=587
spring.mail.username=dms.administrator@ipca.com
spring.mail.password=dm$2Dm1n14
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=EmailRelaySrv.ipca.com

# ===== File Upload Directory =====
dms.upload.directory=D:/dms-uploads